x = read.table("household_power_consumption.txt", header = TRUE, sep = ';')
x$Date <- as.Date(x$Date, "%d/%m/%Y")
x <- with(x,x[(Date >= "2007-02-01" & Date <= "2007-02-02"),])
png(filename = "Plot 1", width = 480, height = 480)
hist(as.numeric(x$Global_active_power), col = "red", main = "Global Active Power", xlab = " Global Active Power (kilowatts)")
dev.off()
